#ifndef __MKZ_DEFINITIONS_IMPORTED__
#define __MKZ_DEFINITIONS_IMPORTED__

#define MKZ_PROJECTIONMODE_PARALLEL 0
#define MKZ_PROJECTIONMODE_PERSPECTIVE 1

#define MKZ_POLYGONMODE_DOTTED GL_POINT
#define MKZ_POLYGONMODE_WIREFRAME GL_LINE
#define MKZ_POLYGONMODE_FILLED GL_FILL

#endif
